name: Multi Platform Workflow

on:
  pull_request:
    branches: [master]

jobs:

  ubuntu-job:
    name: Ubuntu Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display OS Information
        run: uname -a

      - name: Create File
        run: echo "Hello from Ubuntu" > ubuntu.txt

      - name: Display File Content
        run: cat ubuntu.txt


  windows-job:
    name: Windows Job
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display OS Information
        run: systeminfo

      - name: Create File
        run: echo Hello from Windows > windows.txt

      - name: Display File Content
        run: type windows.txt


  macos-job:
    name: MacOS Job
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display OS Information
        run: uname -a

      - name: Create File
        run: echo "Hello from macOS" > macos.txt

      - name: Display File Content
        run: cat macos.txt